Game.create!(name: "Halo", description: "Shooter Game")
Game.create!(name: "Kingdom Hearts", description: "Japanese RPG")
Game.create!(name: "Fire Emblem", description: "Turn Based Strategy Game")
Game.create!(name: "Hitman", description: "Stealth Game")
Game.create!(name: "Tetris", description: "Puzzle Game")
Game.create!(name: "Harvest Moon", description: "Japanese RPG")
Game.create!(name: "Pacman", description: "Arcade Game")
